version: 2.1
description: |
  Mobile Application for Retail (Android)
executors:
  android:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/ma-retail-android
commands:
  restore_and_save_cache:
    steps:
      - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        #      - run:
        #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        #         command: sudo chmod +x ./gradlew
      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
      - save_cache:
        paths:
          - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  analyze:
    steps:
      - run:
        name: Lint code
        command: ./gradlew lint test

  build_apk:
    steps:
      - run:
        name: Build debug APK and release APK
        command: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:assembleDevDebugAndroidTest
jobs:
  build:
    environment:
      JVM_OPTS: -Xmx3200m
    executor:
      name: android
    steps:
      - checkout
      - restore_and_save_cache
      - analyze
      - build_apk
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

workflows:
  ma-retail-android_workflows:
    jobs:
      - build
